using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PauseManager : MonoBehaviour
{
    [SerializeField,Header("ï¿½|ï¿½[ï¿½Yï¿½ï¿½ï¿½É—Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½UI"),Tooltip("ï¿½|ï¿½[ï¿½Yï¿½ï¿½ï¿½É—Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½UI")] GameObject[] PauseUI;
    [Header("ï¿½ï¿½ï¿½^ï¿½Cï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒtï¿½Fï¿½[ï¿½hï¿½Aï¿½Eï¿½gï¿½Ìİ’ï¿½")]
    [SerializeField] SceneLoader _loader;
    [SerializeField] GameObject _fadePanel;
    [SerializeField] Color _color;
    [SerializeField] float _fadeTime;
    [SerializeField] Checkpoint _checkpoint;
    /// <summary>true ï¿½Ìï¿½ï¿½Íˆêï¿½ï¿½~ï¿½Æ‚ï¿½ï¿½ï¿½</summary>
    bool _pauseFlg = false;
    /// <summary>ï¿½fï¿½ï¿½ï¿½Qï¿½[ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½Ïï¿½</summary>
    Action<bool> _onPauseResume;
    /// <summary>ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½éƒŠï¿½Xï¿½g</summary>
    List<IEnumerator> _coroutines = new List<IEnumerator>();
    /// <summary>
    /// ï¿½êï¿½ï¿½~ï¿½Eï¿½ÄŠJï¿½ï¿½ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½Qï¿½[ï¿½gï¿½vï¿½ï¿½ï¿½pï¿½eï¿½B
    /// </summary>
    public Action<bool> OnPauseResume
    {
        get { return _onPauseResume; }
        set { _onPauseResume = value; }
    }

    void Update()
    {
        // ESC ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½êï¿½ï¿½~ï¿½Eï¿½ÄŠJï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (Input.GetButtonDown("Cancel") && !SceneLoader.IsFading)
        {
            PauseResume();
        }
    }
    /// <summary>
    /// ï¿½{ï¿½^ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Åˆêï¿½ï¿½~ï¿½Eï¿½ÄŠJï¿½ï¿½ï¿½é‚½ï¿½ß‚Ìƒï¿½ï¿½\ï¿½bï¿½h
    /// </summary>
    public void PauseResumeByClick()
    {
        PauseResume();
    }
    /// <summary>
    /// ï¿½{ï¿½^ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Åƒï¿½ï¿½^ï¿½Cï¿½Aï¿½ï¿½ï¿½é‚½ï¿½ß‚Ìƒï¿½ï¿½\ï¿½bï¿½h
    /// </summary>
    public void Surrender()
    {
        _checkpoint.ResetPoint();
        _fadePanel.SetActive(true);
        _loader.FadeAndLoadScene(_fadePanel.GetComponent<Image>(), _color, _fadeTime, SceneLoader.Scenes.SelectStage);
    }
    /// <summary>
    /// ï¿½êï¿½ï¿½~ï¿½Eï¿½ÄŠJï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
    /// </summary>
    void PauseResume()
    {
        _pauseFlg = !_pauseFlg;
        _onPauseResume(_pauseFlg);  // ï¿½ï¿½ï¿½ï¿½Å•Ïï¿½ï¿½É‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½ï¿½ï¿½ï¿½iï¿½Sï¿½Äjï¿½Ä‚Ñoï¿½ï¿½ï¿½ï¿½
        foreach (var i in PauseUI)
        {
            i.SetActive(_pauseFlg);
        }
        if (_pauseFlg)
        {
            PauseAllCoroutine();
            Time.timeScale = 0;
        }
        else
        {
            ResumeAllCoroutine();
            Time.timeScale = 1;
        }
    }
    /// <summary>
    /// ï¿½|ï¿½[ï¿½Yï¿½ï¿½ï¿½Ä—~ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B(WaitForSecondsï¿½ï¿½ï¿½gï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½Æ‚ğ„ï¿½)
    /// ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½Ü‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É•Kï¿½ï¿½GetCoroutine()ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½ï¿½IEnumeratorï¿½^ï¿½Ì•Ïï¿½ï¿½É•Û‘ï¿½ï¿½ï¿½ï¿½ï¿½
    /// ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Kï¿½ï¿½1ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ò‚ï¿½ï¿½Ä•Kï¿½ï¿½OnComplete(ï¿½Û‘ï¿½ï¿½ï¿½ï¿½ï¿½IEnumeratorï¿½^ï¿½Ì•Ïï¿½)ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="enumerator"></param>
    public void BeginCoroutine(IEnumerator enumerator)
    {
        _coroutines.Add(enumerator);
        StartCoroutine(enumerator);
    }
    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ò‚ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½bï¿½h
    /// </summary>
    public IEnumerator GetCoroutine()
    {
        return _coroutines[_coroutines.Count - 1];
    }
    void PauseAllCoroutine()
    {
        foreach (IEnumerator enumerator in _coroutines)
        {
            Debug.Log(enumerator);
            StopCoroutine(enumerator);
        }
    }
    void ResumeAllCoroutine()
    {
        foreach (IEnumerator enumerator in _coroutines)
        {
            StartCoroutine(enumerator);
        }
    }
    /// <summary>
    /// ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
    /// ï¿½Ä‚Ô‘Oï¿½ï¿½yield return new WaitForEndOfFrame()ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="enumerator"></param>
    public void OnComplete(IEnumerator enumerator)
    {
        _coroutines.Remove(enumerator);
    }
}
