using UnityEngine;

public class AnotherRoute : MonoBehaviour
{
    [SerializeField, Header("SelectStageï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½SceaneLoderï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g")] SceneLoader _load;
    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½êŠï¿½ğ’´‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½O
    /// </summary>
    public bool _isPast;
    Timer time;

    private void Start()
    {
        time = FindAnyObjectByType<Timer>();
    }

    private void Update()
    {
        if (time._currentTime <= 0) IsAnother();
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    /// </summary>
    private void IsAnother()
    {
        if (_isPast && GameProgressManager.IsGameCompleted)
        {
            GameProgressManager.IsSecretModeUnlocked = true;
            GameProgressManager.HighestClearedStage = 1;
            Checkpoint checkpoint = FindAnyObjectByType<Checkpoint>();
            checkpoint.ResetPoint();
            PlayerPrefs.SetInt("nowStage", GameProgressManager.HighestClearedStage);
            _load.FadeAndLoadScene();
        }
    }
}
